# Generated by Django 5.1.4 on 2024-12-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lock_until',
        ),
    ]
